# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Niles Dorn
tagline:          'A Creative Portfolio'
description:      'A portfolio of indepdendent and professional game development, music production, and sound design projects.'
url:              http://ign1ka.github.io
baseurl:          ''

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          2.0

github:
  repo:           https://github.com/ign1ka
